/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EGOOGLEPLAYGAMES_AUTODEFS_H
#define S3EGOOGLEPLAYGAMES_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GOOGLEPLAYGAMES_NAME "s3eGooglePlayGames"
#define S3E_EXT_GOOGLEPLAYGAMES_HASH 0xadbd9350

#endif /* !S3EGOOGLEPLAYGAMES_AUTODEFS_H */
